package modelo;
// Generated May 25, 2023 2:02:34 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;

/**
 * Funcionario generated by hbm2java
 */
public class Funcionario  implements java.io.Serializable {


     private Integer idFuncionario;
     private Clientes clientes;
     private String nome;
     private String apelido;
     private String endereco;
     private int idade;
     private String email;
     private int telefone;
     private Set vendas = new HashSet(0);

    public Funcionario() {
    }

	
    public Funcionario(Clientes clientes, String nome, String apelido, String endereco, int idade, String email, int telefone) {
        this.clientes = clientes;
        this.nome = nome;
        this.apelido = apelido;
        this.endereco = endereco;
        this.idade = idade;
        this.email = email;
        this.telefone = telefone;
    }
    public Funcionario(Clientes clientes, String nome, String apelido, String endereco, int idade, String email, int telefone, Set vendas) {
       this.clientes = clientes;
       this.nome = nome;
       this.apelido = apelido;
       this.endereco = endereco;
       this.idade = idade;
       this.email = email;
       this.telefone = telefone;
       this.vendas = vendas;
    }

    Funcionario(int cod) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
   
    public Integer getIdFuncionario() {
        return this.idFuncionario;
    }
    
    public void setIdFuncionario(Integer idFuncionario) {
        this.idFuncionario = idFuncionario;
    }
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getApelido() {
        return this.apelido;
    }
    
    public void setApelido(String apelido) {
        this.apelido = apelido;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public int getIdade() {
        return this.idade;
    }
    
    public void setIdade(int idade) {
        this.idade = idade;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public int getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(int telefone) {
        this.telefone = telefone;
    }
    public Set getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Set vendas) {
        this.vendas = vendas;
    }


public String recuperarDados(){
        SessionFactory sessionFactory = new Configuration().configure().buildSessionFactory();
        Session sessao = sessionFactory.openSession();
        Transaction tr=null;
        Iterator it;
        Funcionario funcionario;
        try{
            tr=sessao.beginTransaction();
           Query q=sessao.createQuery("from Funcionario where idFuncionario=:codigo");
            q.setInteger("codigo", this.idFuncionario);
            it=q.list().iterator();
            if(it.hasNext()){
                funcionario=(Funcionario)it.next();
                this.nome=getNome();
                this.apelido=getApelido();
                this.endereco=getEndereco();
                this.idade=getIdade();
                this.email=getEmail();
                this.telefone=getTelefone();
                this.vendas=getVendas();
                
            
            }
            tr.commit();
        
        }catch(Exception e){
            e.printStackTrace();
            tr.rollback();
        }
    
    
    return clientes+", "+nome+", "+apelido+","+endereco+", "+idade+", "+email+", "+telefone+","+vendas;
    }



}


