package modelo;
// Generated May 25, 2023 2:02:34 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;

/**
 * Produtos generated by hbm2java
 */
public class Produtos  implements java.io.Serializable {


     private Integer idProduto;
     private Clientes clientes;
     private Stock stock;
     private String nome;
     private String designacao;
     private int preco;
     private Date dataValidade;
     private int quantidadeProduto;
     private Set vendas = new HashSet(0);

    public Produtos() {
    }

	
    public Produtos(Clientes clientes, Stock stock, String nome, String designacao, int preco, Date dataValidade, int quantidadeProduto) {
        this.clientes = clientes;
        this.stock = stock;
        this.nome = nome;
        this.designacao = designacao;
        this.preco = preco;
        this.dataValidade = dataValidade;
        this.quantidadeProduto = quantidadeProduto;
    }
    public Produtos(Clientes clientes, Stock stock, String nome, String designacao, int preco, Date dataValidade, int quantidadeProduto, Set vendas) {
       this.clientes = clientes;
       this.stock = stock;
       this.nome = nome;
       this.designacao = designacao;
       this.preco = preco;
       this.dataValidade = dataValidade;
       this.quantidadeProduto = quantidadeProduto;
       this.vendas = vendas;
    }
   
    public Integer getIdProduto() {
        return this.idProduto;
    }
    
    public void setIdProduto(Integer idProduto) {
        this.idProduto = idProduto;
    }
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }
    public Stock getStock() {
        return this.stock;
    }
    
    public void setStock(Stock stock) {
        this.stock = stock;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getDesignacao() {
        return this.designacao;
    }
    
    public void setDesignacao(String designacao) {
        this.designacao = designacao;
    }
    public int getPreco() {
        return this.preco;
    }
    
    public void setPreco(int preco) {
        this.preco = preco;
    }
    public Date getDataValidade() {
        return this.dataValidade;
    }
    
    public void setDataValidade(Date dataValidade) {
        this.dataValidade = dataValidade;
    }
    public int getQuantidadeProduto() {
        return this.quantidadeProduto;
    }
    
    public void setQuantidadeProduto(int quantidadeProduto) {
        this.quantidadeProduto = quantidadeProduto;
    }
    public Set getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Set vendas) {
        this.vendas = vendas;
    }

public String recuperarDados(){
        SessionFactory sessionFactory = new Configuration().configure().buildSessionFactory();
        Session sessao = sessionFactory.openSession();
        Transaction tr=null;
        Iterator it;
        Produtos produto;
        try{
            tr=sessao.beginTransaction();
           Query q=sessao.createQuery("from Produtos where idProduto=:codigo");
            q.setInteger("codigo", this.idProduto);
            it=q.list().iterator();
            if(it.hasNext()){
                produto=(Produtos)it.next();
                this.nome=getNome();
                this.designacao=getDesignacao();
                this.preco=getPreco();
                this.dataValidade=getDataValidade();
                this.quantidadeProduto=getQuantidadeProduto();
                this.vendas=getVendas();
                
            
            }
            tr.commit();
        
        }catch(Exception e){
            e.printStackTrace();
            tr.rollback();
        }
    
    
    return nome+","+designacao+", "+preco+", "+dataValidade+", "+quantidadeProduto+","+vendas;
    }





}


