package modelo;
// Generated May 25, 2023 2:02:34 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Iterator;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;

/**
 * Venda generated by hbm2java
 */
public class Venda  implements java.io.Serializable {


     private Integer idVenda;
     private Clientes clientes;
     private Funcionario funcionario;
     private Produtos produtos;
     private Date dataVenda;

    public Venda() {
    }

    public Venda(Clientes clientes, Funcionario funcionario, Produtos produtos, Date dataVenda) {
       this.clientes = clientes;
       this.funcionario = funcionario;
       this.produtos = produtos;
       this.dataVenda = dataVenda;
    }
   
    public Integer getIdVenda() {
        return this.idVenda;
    }
    
    public void setIdVenda(Integer idVenda) {
        this.idVenda = idVenda;
    }
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public Produtos getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Produtos produtos) {
        this.produtos = produtos;
    }
    public Date getDataVenda() {
        return this.dataVenda;
    }
    
    public void setDataVenda(Date dataVenda) {
        this.dataVenda = dataVenda;
    }

public String recuperarDados(){
        SessionFactory sessionFactory = new Configuration().configure().buildSessionFactory();
        Session sessao = sessionFactory.openSession();
        Transaction tr=null;
        Iterator it;
        Venda venda;
        try{
            tr=sessao.beginTransaction();
           Query q=sessao.createQuery("from Venda where idVenda=:codigo");
            q.setInteger("codigo", this.idVenda);
            it=q.list().iterator();
            if(it.hasNext()){
                venda=(Venda)it.next();
                 this.clientes=getClientes();
                this.funcionario=getFuncionario();
                this.produtos=getProdutos();
                this.dataVenda=getDataVenda();
                
            
            }
            tr.commit();
        
        }catch(Exception e){
            e.printStackTrace();
            tr.rollback();
        }
    
    
    return clientes+", "+funcionario+", "+produtos+", "+dataVenda;
    }





}


