package modelos;
// Generated 01/06/2023 18:27:56 by Hibernate Tools 4.3.1



/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private String sexo;
     private Integer idade;

    public Clientes() {
    }

    public Clientes(String nome, String sexo, Integer idade) {
       this.nome = nome;
       this.sexo = sexo;
       this.idade = idade;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public Integer getIdade() {
        return this.idade;
    }
    
    public void setIdade(Integer idade) {
        this.idade = idade;
    }




}


