package modelos;
// Generated 01/06/2023 18:27:56 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CuboPedidos generated by hbm2java
 */
public class CuboPedidos  implements java.io.Serializable {


     private Integer id;
     private Integer idPedido;
     private Date data;
     private Integer idCliente;
     private String nomeCliente;
     private String sexoCliente;
     private Integer idadeCliente;
     private Integer idProduto;
     private String produto;
     private Float precoAtual;
     private Integer qtdeComprada;
     private Float valorPagoUnidade;
     private Float total;

    public CuboPedidos() {
    }

    public CuboPedidos(Integer idPedido, Date data, Integer idCliente, String nomeCliente, String sexoCliente, Integer idadeCliente, Integer idProduto, String produto, Float precoAtual, Integer qtdeComprada, Float valorPagoUnidade, Float total) {
       this.idPedido = idPedido;
       this.data = data;
       this.idCliente = idCliente;
       this.nomeCliente = nomeCliente;
       this.sexoCliente = sexoCliente;
       this.idadeCliente = idadeCliente;
       this.idProduto = idProduto;
       this.produto = produto;
       this.precoAtual = precoAtual;
       this.qtdeComprada = qtdeComprada;
       this.valorPagoUnidade = valorPagoUnidade;
       this.total = total;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getIdPedido() {
        return this.idPedido;
    }
    
    public void setIdPedido(Integer idPedido) {
        this.idPedido = idPedido;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public String getNomeCliente() {
        return this.nomeCliente;
    }
    
    public void setNomeCliente(String nomeCliente) {
        this.nomeCliente = nomeCliente;
    }
    public String getSexoCliente() {
        return this.sexoCliente;
    }
    
    public void setSexoCliente(String sexoCliente) {
        this.sexoCliente = sexoCliente;
    }
    public Integer getIdadeCliente() {
        return this.idadeCliente;
    }
    
    public void setIdadeCliente(Integer idadeCliente) {
        this.idadeCliente = idadeCliente;
    }
    public Integer getIdProduto() {
        return this.idProduto;
    }
    
    public void setIdProduto(Integer idProduto) {
        this.idProduto = idProduto;
    }
    public String getProduto() {
        return this.produto;
    }
    
    public void setProduto(String produto) {
        this.produto = produto;
    }
    public Float getPrecoAtual() {
        return this.precoAtual;
    }
    
    public void setPrecoAtual(Float precoAtual) {
        this.precoAtual = precoAtual;
    }
    public Integer getQtdeComprada() {
        return this.qtdeComprada;
    }
    
    public void setQtdeComprada(Integer qtdeComprada) {
        this.qtdeComprada = qtdeComprada;
    }
    public Float getValorPagoUnidade() {
        return this.valorPagoUnidade;
    }
    
    public void setValorPagoUnidade(Float valorPagoUnidade) {
        this.valorPagoUnidade = valorPagoUnidade;
    }
    public Float getTotal() {
        return this.total;
    }
    
    public void setTotal(Float total) {
        this.total = total;
    }




}


