package modelos;
// Generated 01/06/2023 18:27:56 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pedidos generated by hbm2java
 */
public class Pedidos  implements java.io.Serializable {


     private Integer id;
     private Date data;
     private Integer idCliente;
     private String status;
     private Set pedidosHasProdutoses = new HashSet(0);

    public Pedidos() {
    }

    public Pedidos(Date data, Integer idCliente, String status, Set pedidosHasProdutoses) {
       this.data = data;
       this.idCliente = idCliente;
       this.status = status;
       this.pedidosHasProdutoses = pedidosHasProdutoses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set getPedidosHasProdutoses() {
        return this.pedidosHasProdutoses;
    }
    
    public void setPedidosHasProdutoses(Set pedidosHasProdutoses) {
        this.pedidosHasProdutoses = pedidosHasProdutoses;
    }




}


